### ISSUE TITLE
Text "This item does not have any body text, click the edit tab to change it." should be removed

### ISSUE THREAD

**Issue by zopyx** [collective/collective.glossary#42]
Show this text is not compliant with the standard Plone behavior. If you need a description here then make the Description required. Otherwise an empty description will not show up but please don't force/annoy a user with such a hint/text.

**Comment by hvelarde** [comment]
this has been indeed the standard behavior for years, we took this code from Plone News Item content type:

https://github.com/plone/Products.ATContentTypes/blob/2.3.8/Products/ATContentTypes/skins/ATContentTypes/newsitem_view.pt
