### ISSUE TITLE
Create "Plone 5.2 release", aftwerwards create release with new features

### ISSUE THREAD

**Issue by ksuess** [collective/collective.glossary#56]
@hvelarde Would you please give me access to the repository (AI-team already added me as a pypi maintainer, after waiting for a response from you for a long time). I want to
- revert your merge. 
- merge everything needed for a first release to be compatible with Plone 5.2
- create release
- merge the feature PRs #54 and #55
- create a release

**Comment by ksuess** [comment]
Hi @hvelarde , I would like to move forward with the above mentioned steps. As the repo is protected, my hands are tied. Would you please add me as an admin, thank you.

**Comment by ksuess** [comment]
Hi @collective/staff,  I would like to move forward with the above mentioned steps. As the repo is protected (merge only with review, but maintainer difficult to contact to), my hands are tied. Would you please add me as an admin, thank you.

**Comment by ale-rt** [comment]
Hi @ksuess! You should have the proper rights now. Let me know if this is not the case.

**Comment by ksuess** [comment]
thank you @ale-rt!

**Comment by hvelarde** [comment]
@ksuess sorry, I'm not following this anymore.
