### ISSUE TITLE
Current release does not support Python 3.7 - Needs update of setup.py or conditional use of cached_property

### ISSUE THREAD

**Issue by ksuess** [collective/collective.glossary#68]
_cached_property_ is introduced in Python 3.8
https://docs.python.org/3/library/functools.html#functools.cached_property

**Comment by mauritsvanrees** [comment]
I have a PR to fix this:
https://github.com/collective/collective.glossary/pull/69

**Comment by mauritsvanrees** [comment]
Fixed with 2.1.1.
